---
title: "BIDSapps_Docker"
author: "Nandi"
date: "2 May 2018"
output: html_document
---
These scripts are also saved under 'open_neuroscience_workshop/BIDS_apps/scripts/docker/'

### Download and install Docker for: [Mac](https://docs.docker.com/docker-for-mac/install/) [Windows](https://docs.docker.com/docker-for-windows/install/) [Linux](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

More info about Docker can be found [here](https://neurohackweek.github.io/docker-for-scientists/)
#####Increase Docker's memory useage: Preferences > Advanced > increase the memory limit to maximum > hit "Apply & Restart" 

### Running MRIQC locally using Docker
##### Download mriqc
```{r, engine = 'bash', eval = FALSE}

docker pull poldracklab/mriqc:0.10.4
    #pull image from Docker Hub registry
    #saves image within the depths of Docker (not to the location you downloaded it from)
```

##### Run mriqc
```{r, engine = 'bash', eval = FALSE}

repodir='[path to repo]' # e.g.  ~/Desktop/open_neuroscience_workshop
inputdir=${repodir}/data/bids_data/  #specify directory where bids formatted data lives
outputdir=${repodir}/data/bids_data/derivatives/ #specify output (derivatives) directory

docker run --rm -it -v ${inputdir}:/data:ro -v ${outputdir}:/out poldracklab/mriqc:0.10.4 /data /out participant
    #this command will run container
    #-rm will clean up after container exits
    #-it will run in interactive mode
    #-v gives docker access to the input directory
    # ro = read only
    #"poldracklab/mriqc:0.10.4 /data /out participant" specifies container image, input folder, output folder, and runs analyses on participant level

```
